### ISSUE TITLE
v1.0.0 To-do List

### ISSUE THREAD

**Issue by RandomShovel** [RandomShovel/ShovelBot#1]
- [ ] Integrations
    - [ ] Twitch
        - [ ] Emoticon support for chat display
        - [ ] Badge support for chat display
    - [ ] Beam
        - [ ] Emoticon support for chat display
        - [ ] Badge support for chat display
    - [ ] Hitbox
        - [ ] Emoticon support for chat display
        - [ ] Badge support for chat display
    - [ ] YouTube
        - [ ] Emoticon support for chat display -- Basically emojis
        - [ ] Badge support for chat display
    - [ ] Discord
    - [ ] Unifier (Cross-platform interaction/integration - Excludes Discord)
    - [ ] Emojis support
- [ ] Command Framework
- [ ] Song Request Framework
    - [ ] Song volume caching
- [ ] Quote Framework
- [ ] Custom Command Framework
- [ ] Stream Meta Framework
    - [ ] Alerts for when game mismatches are found on any platform
    - [ ] Alerts for when title mismatches are found on any

**Comment by RandomShovel** [comment]
Split to individual issues.
